### Desarrollo de bases de datos

#### BD Tabular

In [1]:
import pandas as pd

In [2]:
data_prod = pd.read_csv('../fuentes_de_informacion/productos.csv')
data_prod.head()

,id_producto,nombre,categoria,subcategoria,marca,precio_usd,stock,color,potencia_w,capacidad,voltaje,peso_kg,garantia_meses,descripcion
0,P0001,Licuadora,Cocina,Preparación,TechHome,283.63,108,Blanco,650.0,1.2L,12V,5.6,36,"Descubrí el poder de la Licuadora de TechHome,..."
1,P0002,Licuadora,Cocina,Preparación,TechHome,1273.06,114,Rosa,300.0,2.0L,220V,35.9,36,"Descubrí el poder de la Licuadora de TechHome,..."
2,P0003,Plus Licuadora Pro,Cocina,Preparación,TechHome,329.07,97,Negro,700.0,1.2L,220V,47.9,18,Descubrí el poder de la Plus Licuadora Pro de ...
3,P0004,Compacto Licuadora,Cocina,Preparación,ChefMaster,259.42,75,Rosa,1000.0,2.0L,220V,48.7,24,Descubrí el poder de la Compacto Licuadora de ...
4,P0005,Licuadora,Cocina,Preparación,HomeChef,2602.78,97,Azul,1350.0,1.2L,110-220V,49.3,12,"Descubrí el poder de la Licuadora de HomeChef,..."

In [3]:
data_prod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_producto     300 non-null    object
 1   nombre          300 non-null    object
 2   categoria       300 non-null    object
 3   subcategoria    300 non-null    object
 4   marca           300 non-null    object
 5   precio_usd      300 non-null    float64
 6   stock           300 non-null    int64
 7   color           300 non-null    object
 8   potencia_w      298 non-null    float64
 9   capacidad       58 non-null     object
 10  voltaje         300 non-null    object
 11  peso_kg         300 non-null    float64
 12  garantia_meses  300 non-null    int64
 13  descripcion     300 non-null    object
dtypes: float64(3), int64(2), object(9)
memory usage: 32.9+ KB

Construcción de base de datos con SQLite

In [4]:
import requests
import sqlite3
import json
import re

In [5]:
conn = sqlite3.connect("../databases/productos.db")
cursor = conn.cursor()

In [6]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS productos(
id_producto TEXT PRIMARY KEY,
nombre TEXT,
categoria TEXT,
subcategoria TEXT,
marca TEXT,
precio_usd REAL,
stock INTEGER,
color TEXT,
potencia_w REAL,
capacidad REAL,
voltaje TEXT,
peso_kg REAL,
garantia_meses INTEGER,
descripcion TEXT)""")

conn.commit()

In [7]:
cursor.execute("DELETE FROM productos")
conn.commit()

In [8]:
data_prod.to_sql("productos", conn, if_exists="append", index=False)

300

#### BD Vectorial

In [24]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

WARNING:tensorflow:From d:\Programas\anaconda3\envs\Python_ML\lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [15]:
#!pip install chromadb sentence-transformers

In [25]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50,
    separators=["\n", " ", ""])

In [26]:
with open('../fuentes_de_informacion/faqs.json', 'r', encoding="utf-8") as f:
    faqs = json.load(f)
df_faqs = pd.DataFrame(faqs)
df_faqs.head()

,id_faq,id_producto,nombre_producto,categoria,pregunta,respuesta,fecha_publicacion,vistas,util
0,FAQ00001,P0001,Licuadora,Especificaciones,¿Qué voltaje requiere?,El Licuadora funciona con 12V. El consumo es d...,2025-01-05,4067,22
1,FAQ00002,P0001,Licuadora,Mantenimiento,¿Cada cuánto debo hacer mantenimiento?,El Licuadora de TechHome está diseñado para us...,2025-05-18,2556,97
2,FAQ00003,P0001,Licuadora,Uso,¿Es seguro para uso continuo?,El Licuadora de TechHome está diseñado para us...,2024-12-04,1654,19
3,FAQ00004,P0001,Licuadora,Uso,¿Cómo se usa correctamente este producto?,El Licuadora de TechHome está diseñado para us...,2025-08-02,4956,20
4,FAQ00005,P0001,Licuadora,Especificaciones,¿Cuál es el consumo eléctrico?,El Licuadora funciona con 12V. El consumo es d...,2025-06-15,1683,18

In [27]:
df_faqs['contenido'] = (
    "Pregunta: "+df_faqs['pregunta'] +
    "\n Respuesta: "+df_faqs['respuesta']
)

In [28]:
df_faqs["contenido"].apply(lambda x: len(x.split())).describe()

count    3000.000000
mean       36.735667
std         4.251331
min        20.000000
25%        36.000000
50%        38.000000
75%        39.000000
max        43.000000
Name: contenido, dtype: float64

In [29]:
documentos = []
metadatos = []
ids = []

for _, row in df_faqs.iterrows():
    chunks = text_splitter.split_text(row['contenido'])
    for i, chunk in enumerate(chunks):
        documentos.append(chunk)
        metadatos.append({
            'id_producto': row['id_producto'],
            'nombre_producto': row['nombre_producto'],
            'categoria': row['categoria'],
            'fecha_publicacion': row['fecha_publicacion']
        })
        ids.append(f"{row['id_faq']}_{i}")

In [30]:
import chromadb
from chromadb.utils import embedding_functions

In [31]:
funcion_embedding = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

In [32]:
import os

BASE_DIR = os.path.abspath("..")
VECTOR_DB_PATH = os.path.join(BASE_DIR, "databases", "vectores")
os.makedirs(VECTOR_DB_PATH, exist_ok=True)

client = chromadb.PersistentClient(path=VECTOR_DB_PATH)

In [33]:
try:
    client.delete_collection(name='coleccion_faqs')
except:
    pass

coleccion = client.get_or_create_collection(
    name='coleccion_faqs',
    embedding_function=funcion_embedding
)

In [ ]:
coleccion.add(
    documents=documentos,
    metadatas=metadatos,
    ids=ids)

In [36]:
coleccion.count()

3000

#### BD de Grafos

In [37]:
BASE_DIR = os.path.abspath("..")
REVIEWS_PATH = os.path.join(BASE_DIR, "fuentes_de_informacion", "resenas_usuarios")

In [39]:
def parsear_resena(ruta_archivo):
    with open(ruta_archivo, "r", encoding="utf-8") as f:
        lineas = f.readlines()
    
    fecha = lineas[0].split(": ", 1)[1].strip()
    usuario = lineas[1].split(": ", 1)[1].strip()
    producto = lineas[3].split(": ", 1)[1].strip()
    puntaje = lineas[4].split(": ", 1)[1].strip()
    provincia = lineas[5].split(": ", 1)[1].strip()
    
    texto = "".join(lineas[7:]).strip()
    
    return {
        "fecha": fecha,
        "usuario": usuario,
        "producto": producto,
        "puntaje": puntaje,
        "provincia": provincia,
        "texto_resena": texto}

In [40]:
registros = []

for archivo in os.listdir(REVIEWS_PATH):
    if archivo.endswith(".txt"):
        ruta = os.path.join(REVIEWS_PATH, archivo)
        datos = parsear_resena(ruta)
        registros.append(datos)

df_resenas = pd.DataFrame(registros)

In [41]:
df_resenas.head()

,fecha,usuario,producto,puntaje,provincia,texto_resena
0,2024-04-17,Lucía_Acosta,Exprimidor 2024 (P0129),5/5,Tierra del Fuego,Hola a todos! Increíble relación calidad-preci...
1,2025-10-03,Nicolás_Vega,Profesional Batidora de Mano (P0017),5/5,Santa Cruz,Buenas! Mejor de lo que esperaba con Profesion...
2,2025-10-11,Lucía_Flores,Plancha Seca 2024 (P0285),4/5,Santiago del Estero,"Quiero compartir mi experiencia. Me encantó, y..."
3,2025-05-25,Miranda_Fernández,Advanced Procesadora II (P0012),5/5,Río Negro,"Hola a todos! Funciona de 10, muy satisfecho/a..."
4,2025-06-03,Rodrigo_Molina,Elite Plancha Seca X (P0284),5/5,CABA,Buenas! No me arrepiento para nada de la compr...

Se continúa con el preprocesamiento de este dataframe antes de construir la base de datos de grafos.

In [42]:
df_resenas['fecha'] = pd.to_datetime(df_resenas['fecha'])

In [43]:
df_resenas['usuario'] = df_resenas['usuario'].str.replace('_', ' ', regex=False)

In [44]:
df_resenas[['nombre_producto', 'id_producto']] = df_resenas['producto'].str.extract(r'^(.*?)\s\((P\d+)\)$')

In [45]:
df_resenas['puntaje'] = df_resenas['puntaje'].str.split('/').str[0].astype(int)

In [47]:
df_resenas = df_resenas.drop(columns=['producto'])

In [49]:
df_resenas.head()

,fecha,usuario,puntaje,provincia,texto_resena,nombre_producto,id_producto
0,2024-04-17,Lucía Acosta,5,Tierra del Fuego,Hola a todos! Increíble relación calidad-preci...,Exprimidor 2024,P0129
1,2025-10-03,Nicolás Vega,5,Santa Cruz,Buenas! Mejor de lo que esperaba con Profesion...,Profesional Batidora de Mano,P0017
2,2025-10-11,Lucía Flores,4,Santiago del Estero,"Quiero compartir mi experiencia. Me encantó, y...",Plancha Seca 2024,P0285
3,2025-05-25,Miranda Fernández,5,Río Negro,"Hola a todos! Funciona de 10, muy satisfecho/a...",Advanced Procesadora II,P0012
4,2025-06-03,Rodrigo Molina,5,CABA,Buenas! No me arrepiento para nada de la compr...,Elite Plancha Seca X,P0284

Construcción de base de datos con Neo4j

In [38]:
#!pip install neo4j

In [50]:
from neo4j import GraphDatabase

In [51]:
uri = "neo4j+s://a5a91658.databases.neo4j.io"
user = "a5a91658"
password = "pD3DBz-E3P3MRLaKf077DwxQFhi3KEIl1EfE2hxF2LY"

driver = GraphDatabase.driver(uri, auth=(user, password))

with driver.session() as session:
    print(session.run("RETURN 1").single()[0])

1

In [52]:
with driver.session() as session:
    session.run("""
    CREATE CONSTRAINT usuario_id IF NOT EXISTS
    FOR (u:Usuario) REQUIRE u.id_usuario IS UNIQUE
    """)

    session.run("""
    CREATE CONSTRAINT producto_id IF NOT EXISTS
    FOR (p:Producto) REQUIRE p.id_producto IS UNIQUE
    """)

In [53]:
data = df_resenas.to_dict("records")

In [43]:
def cargar_resenas(tx, rows):
    query = """
    UNWIND $rows AS row

    MERGE (u:Usuario {id_usuario: row.usuario})

    MERGE (p:Producto {id_producto: row.id_producto})
    SET p.nombre = row.nombre_producto

    CREATE (r:Reseña {
        fecha: date(row.fecha),
        puntaje: toInteger(row.puntaje),
        texto: row.texto_resena,
        provincia: row.provincia
    })

    MERGE (u)-[:ESCRIBIO]->(r)
    MERGE (r)-[:SOBRE]->(p)
    """
    tx.run(query, rows=rows)

with driver.session() as session:
    session.execute_write(cargar_resenas, data)

### Interfaces de consulta

#### Función de consulta - BD Vectorial

In [54]:
def buscar_faqs(consulta, filtros=None, k=3):
    resultados = coleccion.query(
        query_texts=[consulta],
        n_results=k,
        where=filtros
    )
    return {
        "documentos": resultados["documents"][0],
        "metadatos": resultados["metadatas"][0],
        "distancias": resultados["distances"][0]
    }

In [57]:
#Prueba:
buscar_faqs(consulta="¿Es normal que se caliente?",
    filtros={"nombre_producto": "Licuadora"}, k=3)

{'documentos': ['Pregunta: ¿Cuál es el consumo eléctrico?\n Respuesta: El Licuadora funciona con 12V. El consumo es de 650W. Recomendamos usar un estabilizador de tensión.',
  'Pregunta: ¿Cuál es el consumo eléctrico?\n Respuesta: El Licuadora funciona con 110-220V. El consumo es de 1350W. Recomendamos usar un estabilizador de tensión.',
  'Pregunta: ¿Qué voltaje requiere?\n Respuesta: El Licuadora funciona con 12V. El consumo es de 650W. Recomendamos usar un estabilizador de tensión.'],
 'metadatos': [{'id_producto': 'P0001',
   'categoria': 'Especificaciones',
   'nombre_producto': 'Licuadora',
   'fecha_publicacion': '2025-06-15'},
  {'fecha_publicacion': '2025-08-15',
   'categoria': 'Especificaciones',
   'nombre_producto': 'Licuadora',
   'id_producto': 'P0005'},
  {'id_producto': 'P0001',
   'categoria': 'Especificaciones',
   'nombre_producto': 'Licuadora',
   'fecha_publicacion': '2025-01-05'}],
 'distancias': [0.7439897060394287, 0.7515973448753357, 0.7902710437774658]}

#### Función de consulta - BD Tabular

In [64]:
columnas_categoricas = ["categoria", "subcategoria", "marca", "color", "voltaje"]
columnas_numericas   = ["precio_usd", "stock", "potencia_w", "capacidad", "peso_kg", "garantia_meses"]

metadata_str = "Información del dataset:\n"
metadata_str += f"- Total de registros: {len(df_productos)}\n"

metadata_str += "\nCampos categóricos y sus valores únicos:\n"
for col in columnas_categoricas:
    valores = df_productos[col].dropna().unique().tolist()
    metadata_str += f"  - {col}: {valores}\n"

metadata_str += "\nCampos numéricos con sus rangos:\n"
for col in columnas_numericas:
    mn = df_productos[col].dropna().min()
    mx = df_productos[col].dropna().max()
    metadata_str += f"  - {col}: min={mn}, max={mx}\n"

print(metadata_str)

Información del dataset:
- Total de registros: 300

Campos categóricos y sus valores únicos:
  - categoria: ['Cocina', 'Climatización', 'Lavado', 'Audio y Video']
  - subcategoria: ['Preparación', 'Cocción', 'Refrigeración', 'Pequeños Electrodomésticos', 'Aires Acondicionados', 'Calefacción', 'Ventilación', 'Purificación', 'Lavado de Ropa', 'Secado', 'Lavado de Vajilla', 'Planchado', 'Televisores']
  - marca: ['TechHome', 'ChefMaster', 'HomeChef', 'KitchenPro', 'CookElite', 'PureAir', 'EcoClima', 'ClimaTech', 'ThermoControl', 'AirFlow', 'WashPro', 'SparkleHome', 'CleanMaster', 'LaundryTech', 'FreshWash', 'VisionPro', 'ScreenPro']
  - color: ['Blanco', 'Rosa', 'Negro', 'Azul', 'Dorado', 'Gris', 'Plateado', 'Verde', 'Rojo', 'Amarillo']
  - voltaje: ['12V', '220V', '110-220V']

Campos numéricos con sus rangos:
  - precio_usd: min=28.22, max=2992.33
  - stock: min=1, max=200
  - potencia_w: min=40.0, max=1950.0
  - capacidad: min=1.0L, max=9kg
  - peso_kg: min=0.6, max=49.4
  - garantia_meses: min=6, max=36

In [176]:
system_prompt_tabular = f"""
Sos un experto en bases de datos SQL.
A partir de una consulta en lenguaje natural, debés generar únicamente un objeto JSON con filtros válidos para la tabla productos.

{metadata_str}

Columnas disponibles: id_producto, nombre, categoria, subcategoria, marca, precio_usd, stock, color, potencia_w, capacidad, voltaje, peso_kg, garantia_meses, descripcion.

Estructura del JSON:
- Igualdad: "columna": "valor"
- Comparación numérica (precio_usd, stock, potencia_w, capacidad, peso_kg, garantia_meses):
  "columna": {{"<": valor}} | {{"<=": valor}} | {{">": valor}} | {{">=": valor}}
- Búsqueda por texto parcial (nombre, marca, color, descripcion):
  "columna": {{"LIKE": "%valor%"}}

Nota importante: cuando la consulta menciona un tipo de producto específico como
'licuadora', 'cafetera', 'heladera', etc., filtrá por la columna 'nombre' usando LIKE,
no por 'categoria'.

Ejemplos:
Consulta: "Productos de cocina con precio menor a 500 dólares"
Respuesta: {{"categoria": "Cocina", "precio_usd": {{"<": 500}}}}

Consulta: "¿Cuáles son las licuadoras de menos de $200?"
Respuesta: {{"nombre": {{"LIKE": "%licuadora%"}}, "precio_usd": {{"<": 200}}}}

Consulta: "Mostrar cafeteras de la marca Oster"
Respuesta: {{"nombre": {{"LIKE": "%cafetera%"}}, "marca": {{"LIKE": "%Oster%"}}}}

Devolvé únicamente JSON válido, sin texto antes ni después. Si no hay filtros, devolvé {{}}.
"""

El modelo Llama 3.2 genera un filtro en base al texto del usuario, en un formato JSON.

In [66]:
def generar_filtros(consulta_usuario):
    url = "http://localhost:11434/api/generate"
    payload = {
        "model": "llama3.2",
        "prompt": f"{system_prompt_tabular}\n\nConsulta del usuario:\n{consulta_usuario}",
        "stream": False,
        "options": {"temperature": 0}
    }
    response = requests.post(url, json=payload)
    resultado = response.json()["response"]

    # Extracción robusta del JSON por si el LLM agrega texto extra
    match = re.search(r'\{.*\}', resultado, re.DOTALL)
    if not match:
        return {}
    try:
        return json.loads(match.group())
    except json.JSONDecodeError:
        return {}

In [67]:
#Prueba
consulta = "Mostrar productos de climatización con precio menor a 1000 dólares y garantía mayor a 12 meses"
res1 = generar_filtros(consulta)
res1

{'categoria': 'Climatización',
 'precio_usd': {'<': 1000},
 'garantia_meses': {'>=': 12}}

In [68]:
#Prueba2
consulta2 = "Mostrar lavarropas de menos de 200 dólares, con al menos 6 meses de garantía"
res2 = generar_filtros(consulta2)
res2

{'categoria': 'Lavado', 'precio_usd': {'<': 200}, 'garantia_meses': {'>=': 6}}

Se construyen los filtros para usar como WHERE sobre la base de datos tabular.

In [177]:
def construir_where(filtros):
    condiciones = []
    valores = []
    for columna, valor in filtros.items():
        if not isinstance(valor, dict):
            condiciones.append(f"{columna} = ?")
            valores.append(valor)
        else:
            for operador, numero in valor.items():
                if operador == "LIKE":
                    condiciones.append(f"{columna} LIKE ?")
                    valores.append(numero)
                else:
                    condiciones.append(f"{columna} {operador} ?")
                    valores.append(numero)
    if not condiciones:
        return "", []
    return "WHERE " + " AND ".join(condiciones), valores

In [70]:
columnas_validas = {
    'id_producto', 'nombre', 'categoria', 'subcategoria',
    'marca', 'precio_usd', 'stock', 'color',
    'potencia_w', 'capacidad', 'voltaje',
    'peso_kg', 'garantia_meses', 'descripcion'
}

def buscar_productos(consulta_usuario, conexion=None):
    if conexion is None:
        conexion = conn

    filtros = generar_filtros(consulta_usuario)

    for columna in filtros.keys():
        if columna not in columnas_validas:
            return f"Error: columna inválida detectada: {columna}"

    where_clause, valores = construir_where(filtros)
    query = f"SELECT * FROM productos {where_clause};"

    # Devuelve DataFrame en lugar de tuplas crudas para mejor legibilidad
    return pd.read_sql(query, conexion, params=valores)

In [71]:
consulta = "Mostrar productos de cocción con precio mayor a 100 dólares"
buscar_productos(consulta)

,id_producto,nombre,categoria,subcategoria,marca,precio_usd,stock,color,potencia_w,capacidad,voltaje,peso_kg,garantia_meses,descripcion
0,P0001,Licuadora,Cocina,Preparación,TechHome,283.63,108,Blanco,650.0,1.2L,12V,5.6,36,"Descubrí el poder de la Licuadora de TechHome,..."
1,P0002,Licuadora,Cocina,Preparación,TechHome,1273.06,114,Rosa,300.0,2.0L,220V,35.9,36,"Descubrí el poder de la Licuadora de TechHome,..."
2,P0003,Plus Licuadora Pro,Cocina,Preparación,TechHome,329.07,97,Negro,700.0,1.2L,220V,47.9,18,Descubrí el poder de la Plus Licuadora Pro de ...
3,P0004,Compacto Licuadora,Cocina,Preparación,ChefMaster,259.42,75,Rosa,1000.0,2.0L,220V,48.7,24,Descubrí el poder de la Compacto Licuadora de ...
4,P0005,Licuadora,Cocina,Preparación,HomeChef,2602.78,97,Azul,1350.0,1.2L,110-220V,49.3,12,"Descubrí el poder de la Licuadora de HomeChef,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,P0143,Elite Deshidratador,Cocina,Pequeños Electrodomésticos,CookElite,1521.14,107,Plateado,1600.0,None,110-220V,38.6,24,Presentamos la Elite Deshidratador de CookElit...
137,P0144,Plus Deshidratador 2024,Cocina,Pequeños Electrodomésticos,KitchenPro,2141.41,132,Negro,1700.0,None,110-220V,27.9,6,Presentamos la Plus Deshidratador 2024 de Kitc...
138,P0145,Deshidratador,Cocina,Pequeños Electrodomésticos,ChefMaster,297.84,56,Gris,1600.0,None,12V,7.8,24,"Presentamos la Deshidratador de ChefMaster, un..."
139,P0146,Ultra Deshidratador,Cocina,Pequeños Electrodomésticos,ChefMaster,1140.36,7,Verde,1800.0,None,110-220V,12.2,6,Presentamos la Ultra Deshidratador de ChefMast...
140,P0147,Turbo Deshidratador,Cocina,Pequeños Electrodomésticos,TechHome,2095.80,35,Gris,650.0,None,220V,2.4,24,Presentamos la Turbo Deshidratador de TechHome...

#### Función de consulta - BD de Grafos

In [100]:
schema_grafo = """
Nodos:
- Usuario {id_usuario, telefono, provincia}
- Producto {id_producto, nombre}
- Reseña {fecha, puntaje, texto}

Relaciones:
- (Usuario)-[:ESCRIBIO]->(Reseña)
- (Reseña)-[:SOBRE]->(Producto)

Puntaje es un entero del 1 al 5.
"""

In [101]:
system_prompt_grafo = f"""
Sos un experto en bases de datos de grafos con Neo4j.
A partir de una consulta en lenguaje natural, generá únicamente una query Cypher válida, sin explicaciones ni comentarios.

{schema_grafo}

Ejemplos:

Consulta: ¿Qué opinan los usuarios de la cafetera?
MATCH (u:Usuario)-[:ESCRIBIO]->(r:Reseña)-[:SOBRE]->(p:Producto)
WHERE toLower(p.nombre) CONTAINS 'cafetera'
RETURN u.id_usuario, r.puntaje, r.texto, p.nombre

Consulta: Mostrar productos con puntaje mayor a 4
MATCH (r:Reseña)-[:SOBRE]->(p:Producto)
WHERE r.puntaje > 4
RETURN p.nombre, r.puntaje, r.texto

Consulta: ¿Cuáles son los productos peor valorados?
MATCH (r:Reseña)-[:SOBRE]->(p:Producto)
RETURN p.nombre, avg(r.puntaje) AS puntaje_promedio
ORDER BY puntaje_promedio ASC
LIMIT 10

Consulta: ¿Qué productos están relacionados con la categoría Cocina?
MATCH (r:Reseña)-[:SOBRE]->(p:Producto)
RETURN DISTINCT p.nombre, p.id_producto

Devolvé únicamente la query Cypher, sin texto antes ni después.
"""

Se asegura que la respuesta de la LLM tenga el formato limpio, sin agregados.

In [102]:
def limpiar_cypher(respuesta_modelo):
    # Busca bloque ```cypher ... ``` o ``` ... ```
    match = re.search(r"```(?:cypher)?\s*(.*?)```", respuesta_modelo, re.DOTALL)
    if match:
        return match.group(1).strip()
    
    # Si no hay markdown, devuelve el texto limpio
    return respuesta_modelo.strip()

In [103]:
def generar_cypher(consulta_usuario):
    prompt = f"{system_prompt_grafo}\n\nConsulta:\n{consulta_usuario}"

    payload = {
        "model": "llama3.2",
        "prompt": prompt,
        "stream": False,
        "temperature": 0}

    response = requests.post("http://localhost:11434/api/generate", json=payload)
    respuesta_cruda = response.json()["response"]
    
    return limpiar_cypher(respuesta_cruda)

Prueba de la respuesta del LLM con respecto a las query Cypher.

In [104]:
consulta_gr = "Mostrar productos cuyas reseñas son iguales a 2"
print(generar_cypher(consulta_gr))

MATCH (r:Reseña)-[:SOBRE]->(p:Producto)
WHERE r.puntaje = 2
RETURN p.nombre

In [105]:
def ejecutar_cypher(query):
    with driver.session() as session:
        result = session.run(query)
        return [record.data() for record in result]

Interfaz final para el usuario.

In [106]:
def buscar_en_grafo(consulta_usuario):
    cypher_raw = generar_cypher(consulta_usuario)
    cypher = limpiar_cypher(cypher_raw)
    print(f"[Cypher generado]: {cypher}\n")

    # Validar que el Cypher tenga RETURN antes de ejecutar
    if "RETURN" not in cypher.upper():
        # Reintentar una vez con instrucción explícita
        cypher_raw = generar_cypher(consulta_usuario + " (incluí cláusula RETURN en la query)")
        cypher = limpiar_cypher(cypher_raw)
        print(f"[Cypher regenerado]: {cypher}\n")

    if "RETURN" not in cypher.upper():
        return "Error: el modelo generó una query Cypher incompleta. Reformulá la consulta."

    try:
        return ejecutar_cypher(cypher)
    except Exception as e:
        return f"Error al ejecutar la query: {e}"

In [107]:
print(buscar_en_grafo(consulta_gr))

[Cypher generado]: MATCH (r:Reseña)-[:SOBRE]->(p:Producto)
WHERE r.puntaje = 2
RETURN p.nombre, p.id_producto


### Desarrollo de Clasificador de Intención avanzado

#### Clasificador basado en LLM

In [125]:
system_prompt_class = """<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Clasificá la consulta en exactamente una de estas categorías: TABULAR, VECTORIAL o GRAFO.
Respondé únicamente con el nombre de la categoría, sin explicaciones ni caracteres extra.

Ejemplos:

Consulta: ¿Cuáles son las licuadoras de menos de $200?
TABULAR

Consulta: ¿Qué productos tienen garantía mayor a 2 años?
TABULAR

Consulta: ¿Cuántos watts tiene la licuadora?
TABULAR

Consulta: Mostrar el stock de los productos de ventilación
TABULAR

Consulta: ¿Cuáles son los productos más baratos de climatización?
TABULAR

Consulta: ¿Qué colores están disponibles en los productos de cocción?
TABULAR

Consulta: ¿Qué marcas de heladeras hay?
TABULAR

Consulta: ¿Cuáles son las categorías disponibles?
TABULAR

Consulta: ¿Qué subcategorías existen en climatización?
TABULAR

Consulta: ¿Cómo limpiar correctamente la cafetera?
VECTORIAL

Consulta: ¿Cuál es la diferencia entre una licuadora y una procesadora?
VECTORIAL

Consulta: ¿Para qué sirve la función turbo de la licuadora?
VECTORIAL

Consulta: ¿Cómo afecta la capacidad del bowl al rendimiento de la procesadora?
VECTORIAL

Consulta: ¿En qué consiste la garantía del producto?
VECTORIAL

Consulta: ¿Cómo se instala el aire acondicionado?
VECTORIAL

Consulta: ¿Qué debo tener en cuenta al comprar una cafetera?
VECTORIAL

Consulta: ¿Qué opinan los usuarios de la cafetera?
GRAFO

Consulta: Mostrar productos con puntaje mayor a 4 estrellas
GRAFO

Consulta: Quiero una licuadora con buenas reseñas
GRAFO

Consulta: ¿Qué productos están relacionados con la categoría Cocina?
GRAFO

Consulta: ¿Cuáles son los electrodomésticos mejor calificados?
GRAFO

Consulta: ¿Qué comentarios tienen los usuarios sobre el ventilador?
GRAFO

Consulta: ¿Cuál es la cafetera más recomendada por los usuarios?
GRAFO

Consulta: ¿Cuáles son los productos peor valorados?
GRAFO

--- Casos contrastivos VECTORIAL vs GRAFO ---

Consulta: ¿Qué licuadora me recomendás?
VECTORIAL

Consulta: ¿Qué licuadora recomiendan los usuarios?
GRAFO

Consulta: ¿Cuál es la mejor cafetera?
VECTORIAL

Consulta: ¿Cuál es la cafetera mejor puntuada?
GRAFO

Consulta: ¿Qué productos son buenos para cocinar?
VECTORIAL

Consulta: ¿Qué productos de cocina tienen mejores calificaciones?
GRAFO

Consulta: ¿Me podés recomendar un ventilador?
VECTORIAL

Consulta: ¿Cuál es el ventilador con mejores reseñas?
GRAFO

Consulta: ¿Qué electrodomésticos son ideales para una cocina pequeña?
VECTORIAL

Consulta: ¿Qué electrodomésticos tienen puntajes de 5?
GRAFO

<|eot_id|><|start_header_id|>user<|end_header_id|>

Consulta: {query}

<|eot_id|><|start_header_id|>assistant<|end_header_id|>
"""

In [119]:
def limpiar_respuesta_llm(respuesta_llm):
    if not isinstance(respuesta_llm, str):
        return "ERROR"

    etiqueta = respuesta_llm.strip().upper()
    etiqueta = etiqueta.replace(".", "")
    etiqueta = etiqueta.replace("\n", "")
    etiqueta = etiqueta.replace("\r", "")

    etiquetas_validas = {"TABULAR", "VECTORIAL", "GRAFO"}
    if etiqueta in etiquetas_validas:
        return etiqueta
    
    return "ERROR"

In [120]:
def clasificar_intencion_llm(consulta):
    url = "http://localhost:11434/api/generate"
    payload = {
        "model": "llama3.2",
        "prompt": system_prompt_class.format(query=consulta),  # ← fix
        "stream": False,
        "options": {"temperature": 0}  # ← fix
    }

    response = requests.post(url, json=payload)
    resultado = response.json()["response"]

    return limpiar_respuesta_llm(resultado)

In [121]:
pregunta1 = "Colores disponibles de productos de cocción"
a = clasificar_intencion_llm(pregunta2)
a

'TABULAR'

In [124]:
pregunta2 = "¿Qué productos tienen puntaje menor a 2?"
b = clasificar_intencion_llm(pregunta2)
b

'TABULAR'

In [122]:
def clasif_llm(consulta, filtro=None):
    tipo_base = clasificar_intencion_llm(consulta)

    if tipo_base == "ERROR":
        return {
            "intencion_detectada": "ERROR",
            "resultado": "Error en la clasificación de la consulta"
        }

    if tipo_base == "TABULAR":
        resultado = buscar_productos(consulta)

    elif tipo_base == "VECTORIAL":
        resultado = buscar_faqs(consulta, filtro)

    elif tipo_base == "GRAFO":
        resultado = buscar_en_grafo(consulta)

    else:
        return {
            "intencion_detectada": "ERROR",
            "resultado": "Intención no reconocida"}

    return {
        "intencion_detectada": tipo_base,
        "resultado": resultado
    }

In [127]:
print(clasif_llm(pregunta2)) # rever

{'intencion_detectada': 'TABULAR', 'resultado': Empty DataFrame
Columns: [id_producto, nombre, categoria, subcategoria, marca, precio_usd, stock, color, potencia_w, capacidad, voltaje, peso_kg, garantia_meses, descripcion]
Index: []}

#### Clasificador de intenciones con aprendizaje supervisado

Dataset con preguntas sintéticas

In [130]:
preguntas = [
    # TABULAR
    ("Mostrar productos con precio menor a 500", "TABULAR"),
    ("¿Qué marcas de heladeras hay disponibles?", "TABULAR"),
    ("Lavarropas con potencia mayor a 1000 watts", "TABULAR"),
    ("Mostrar productos de ventilación en color blanco o negro", "TABULAR"),
    ("Productos de cocción con más de seis meses de garantía", "TABULAR"),
    ("¿Cuáles son las licuadoras de menos de $200?", "TABULAR"),
    ("¿Qué voltaje requiere el rallador eléctrico?", "TABULAR"),
    ("Dame los productos con garantía mayor a 1 año", "TABULAR"),
    ("¿Cuántos watts tiene la licuadora modelo X?", "TABULAR"),
    ("Mostrar el stock de los productos de ventilación", "TABULAR"),
    ("¿Qué productos tienen más de 500 unidades en stock?", "TABULAR"),
    ("Filtrar cafeteras por precio entre $100 y $300", "TABULAR"),
    ("¿Cuál es el peso del microondas modelo Z?", "TABULAR"),
    ("Mostrar productos de la marca Samsung disponibles", "TABULAR"),
    ("¿Qué lavarropas tienen capacidad mayor a 8 kilos?", "TABULAR"),
    ("Listar productos con descuento mayor al 20%", "TABULAR"),
    ("¿Cuál es la potencia del horno eléctrico más vendido?", "TABULAR"),
    ("Mostrar heladeras de dos puertas disponibles", "TABULAR"),
    ("¿Qué productos tienen garantía de 2 años?", "TABULAR"),
    ("Listar aires acondicionados de 3000 frigorías", "TABULAR"),
    ("¿Cuánto cuesta el lavavajillas modelo A?", "TABULAR"),
    ("Mostrar productos con stock menor a 10 unidades", "TABULAR"),
    ("¿Qué cafeteras tienen menos de 1000 watts?", "TABULAR"),
    ("Filtrar ventiladores por color negro", "TABULAR"),
    ("¿Cuáles son los productos de menos de $5000 en cocina?", "TABULAR"),

    # VECTORIAL
    ("¿Cómo funciona un aire acondicionado inverter?", "VECTORIAL"),
    ("Diferencia entre horno eléctrico y a gas", "VECTORIAL"),
    ("¿Cuál conviene más para espacios pequeños?", "VECTORIAL"),
    ("¿Cómo se cuidan las ollas de teflón?", "VECTORIAL"),
    ("¿Cómo extiendo la garantía de mi heladera?", "VECTORIAL"),
    ("¿Cómo uso mi licuadora para hacer smoothies?", "VECTORIAL"),
    ("¿Cómo limpiar correctamente la cafetera?", "VECTORIAL"),
    ("¿Para qué sirve la función turbo de la licuadora?", "VECTORIAL"),
    ("¿Qué debo tener en cuenta al comprar una cafetera?", "VECTORIAL"),
    ("¿Cómo se instala el aire acondicionado?", "VECTORIAL"),
    ("¿Cuál es la mejor forma de usar el lavavajillas?", "VECTORIAL"),
    ("¿Por qué es importante el voltaje en los electrodomésticos?", "VECTORIAL"),
    ("¿Cómo afecta la capacidad del bowl al rendimiento de la procesadora?", "VECTORIAL"),
    ("¿En qué consiste la garantía del producto?", "VECTORIAL"),
    ("¿Qué licuadora me recomendás para hacer jugos todos los días?", "VECTORIAL"),
    ("¿Cómo descongelar correctamente una heladera?", "VECTORIAL"),
    ("¿Cuál es la diferencia entre una licuadora y una procesadora?", "VECTORIAL"),
    ("¿Qué electrodomésticos son ideales para una cocina pequeña?", "VECTORIAL"),
    ("¿Cómo puedo ahorrar energía con mi aire acondicionado?", "VECTORIAL"),
    ("¿Qué tipo de detergente usar en el lavavajillas?", "VECTORIAL"),
    ("¿Cómo programar el lavarropas para ropa delicada?", "VECTORIAL"),
    ("¿Qué significa el modo eco en los electrodomésticos?", "VECTORIAL"),
    ("¿Me podés recomendar un ventilador para una habitación grande?", "VECTORIAL"),
    ("¿Cómo funciona el sistema de autolimpieza del horno?", "VECTORIAL"),
    ("¿Qué productos son buenos para cocinar al vapor?", "VECTORIAL"),

    # GRAFO
    ("Productos con puntaje menor a 2", "GRAFO"),
    ("Mostrar reseñas negativas de ventiladores", "GRAFO"),
    ("Usuarios que dejaron opiniones de 5 estrellas", "GRAFO"),
    ("Mostrar los productos con puntajes menores a tres", "GRAFO"),
    ("Mostrar usuarios que reseñaron televisores", "GRAFO"),
    ("¿Qué opinan los usuarios de la cafetera?", "GRAFO"),
    ("¿Cuáles son los electrodomésticos mejor calificados?", "GRAFO"),
    ("¿Qué comentarios tienen los usuarios sobre el ventilador?", "GRAFO"),
    ("¿Cuál es la cafetera más recomendada por los usuarios?", "GRAFO"),
    ("¿Qué productos tienen más de 100 reseñas positivas?", "GRAFO"),
    ("¿Cuáles son los productos peor valorados?", "GRAFO"),
    ("¿Qué otros productos compran los usuarios que llevan esta licuadora?", "GRAFO"),
    ("Quiero una licuadora con buenas reseñas", "GRAFO"),
    ("¿Qué productos están relacionados con la categoría Cocina?", "GRAFO"),
    ("¿Cuál es la heladera mejor puntuada por los compradores?", "GRAFO"),
    ("¿Qué usuarios calificaron con 1 estrella?", "GRAFO"),
    ("Mostrar productos con calificación promedio mayor a 4", "GRAFO"),
    ("¿Qué licuadora recomiendan los usuarios?", "GRAFO"),
    ("¿Cuál es el lavarropas con mejores comentarios?", "GRAFO"),
    ("¿Qué productos de cocina tienen mejores calificaciones?", "GRAFO"),
    ("¿Cuál es el ventilador con mejores reseñas?", "GRAFO"),
    ("¿Qué electrodomésticos tienen más opiniones favorables?", "GRAFO"),
    ("Mostrar los 5 productos más reseñados", "GRAFO"),
    ("¿Qué cafetera tiene mayor cantidad de valoraciones positivas?", "GRAFO"),
    ("¿Cuáles son las opiniones sobre el microondas modelo B?", "GRAFO")]

In [131]:
consultas = [p[0] for p in preguntas]
etiquetas = [p[1] for p in preguntas]

In [132]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(etiquetas)

In [133]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [134]:
modelo = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2),
        lowercase=True,
        stop_words=None  # No hay lista de stop words en español en sklearn, mejor dejarla en None
    )),
    ("clf", LogisticRegression(max_iter=1000, C=1.0))
])

In [135]:
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, f1_score
import numpy as np

In [136]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [137]:
resultados = cross_validate(
    modelo, consultas, y,
    cv=skf,
    scoring={
        "accuracy": "accuracy",
        "f1_macro": make_scorer(f1_score, average="macro")
    },
    return_train_score=True
)

In [138]:
print("=== Evaluación con StratifiedKFold (5 folds) ===")
print(f"Accuracy promedio : {resultados['test_accuracy'].mean():.3f} ± {resultados['test_accuracy'].std():.3f}")
print(f"F1 macro promedio : {resultados['test_f1_macro'].mean():.3f} ± {resultados['test_f1_macro'].std():.3f}")

=== Evaluación con StratifiedKFold (5 folds) ===
Accuracy promedio : 0.747 ± 0.050
F1 macro promedio : 0.743 ± 0.046

In [145]:
modelo.fit(consultas, y)

Pipeline(steps=[('tfidf', TfidfVectorizer(ngram_range=(1, 2))),
                ('clf', LogisticRegression(max_iter=1000))])

In [140]:
y_pred = modelo.predict(consultas)
print("\n=== Classification Report (entrenamiento completo) ===")
print(classification_report(y, y_pred, target_names=le.classes_))

=== Classification Report (entrenamiento completo) ===
              precision    recall  f1-score   support

       GRAFO       1.00      1.00      1.00        25
     TABULAR       1.00      1.00      1.00        25
   VECTORIAL       1.00      1.00      1.00        25

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75

#### Comparación entre modelos clasificadores de intención avanzado

In [141]:
from sklearn.metrics import classification_report, accuracy_score, f1_score
from sklearn.model_selection import train_test_split

In [147]:
X_train, X_test, y_train, y_test = train_test_split(
    consultas, y, test_size=0.2, random_state=42, stratify=y)

In [148]:
#Modelo REG LOG
modelo.fit(X_train, y_train)
y_pred_trad = modelo.predict(X_test)

#Modelo con LLM
y_pred_llm_labels = [clasificar_intencion_llm(c) for c in X_test]
y_pred_llm = le.transform(y_pred_llm_labels)

In [149]:
print("=== TF-IDF + Logistic Regression ===")
print(classification_report(y_test, y_pred_trad, target_names=le.classes_))

=== TF-IDF + Logistic Regression ===
              precision    recall  f1-score   support

       GRAFO       1.00      0.40      0.57         5
     TABULAR       0.80      0.80      0.80         5
   VECTORIAL       0.62      1.00      0.77         5

    accuracy                           0.73        15
   macro avg       0.81      0.73      0.71        15
weighted avg       0.81      0.73      0.71        15

In [150]:
print("=== LLM Few-Shot (Llama 3.2) ===")
print(classification_report(y_test, y_pred_llm, target_names=le.classes_))

=== LLM Few-Shot (Llama 3.2) ===
              precision    recall  f1-score   support

       GRAFO       1.00      0.20      0.33         5
     TABULAR       0.38      1.00      0.56         5
   VECTORIAL       1.00      0.20      0.33         5

    accuracy                           0.47        15
   macro avg       0.79      0.47      0.41        15
weighted avg       0.79      0.47      0.41        15

In [151]:
print("=== Comparación Final ===")
print(f"{'Modelo':<35} {'Accuracy':>10} {'F1 Macro':>10}")
print("-" * 57)
print(f"{'TF-IDF + Logistic Regression':<35} "
      f"{accuracy_score(y_test, y_pred_trad):>10.3f} "
      f"{f1_score(y_test, y_pred_trad, average='macro'):>10.3f}")
print(f"{'LLM Few-Shot (Llama 3.2)':<35} "
      f"{accuracy_score(y_test, y_pred_llm):>10.3f} "
      f"{f1_score(y_test, y_pred_llm, average='macro'):>10.3f}")

=== Comparación Final ===
Modelo                                Accuracy   F1 Macro
---------------------------------------------------------
TF-IDF + Logistic Regression             0.733      0.714
LLM Few-Shot (Llama 3.2)                 0.467      0.407

### Pipeline de Recuperación

In [153]:
#!pip install rank_bm25

In [154]:
from rank_bm25 import BM25Okapi
from sentence_transformers import CrossEncoder

In [155]:
reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

d:\Programas\anaconda3\envs\Python_ML\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\icrui\.cache\huggingface\hub\models--cross-encoder--ms-marco-MiniLM-L-6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

In [156]:
# Recuperamos todos los documentos de ChromaDB para construir el índice BM25
todos = coleccion.get()
corpus_docs = todos["documents"]        # textos
corpus_ids  = todos["ids"]              # ids correspondientes
corpus_meta = todos["metadatas"]        # metadatos correspondientes

# BM25 trabaja con tokens, no con texto crudo
corpus_tokenizado = [doc.lower().split() for doc in corpus_docs]
bm25 = BM25Okapi(corpus_tokenizado)

In [157]:
def buscar_hibrido_rerank(consulta, filtros=None, k=5, k_final=3):
    """
    Búsqueda híbrida (semántica + BM25) con ReRank.

    Args:
        consulta  : texto de la consulta del usuario
        filtros   : dict de metadatos para filtrar en ChromaDB (opcional)
        k         : cantidad de resultados a recuperar por cada método
        k_final   : cantidad de resultados a devolver tras el rerank

    Returns:
        lista de dicts con documento, metadato y score de rerank
    """

    # ── 1. Búsqueda semántica con ChromaDB ────────────────────────────────────
    res_semantica = coleccion.query(
        query_texts=[consulta],
        n_results=k,
        where=filtros
    )
    docs_semantica  = res_semantica["documents"][0]
    metas_semantica = res_semantica["metadatas"][0]
    ids_semantica   = res_semantica["ids"][0]

    # ── 2. Búsqueda por palabras clave con BM25 ───────────────────────────────
    tokens_consulta = consulta.lower().split()
    scores_bm25     = bm25.get_scores(tokens_consulta)
    top_k_indices   = np.argsort(scores_bm25)[::-1][:k]

    docs_bm25  = [corpus_docs[i]  for i in top_k_indices]
    metas_bm25 = [corpus_meta[i]  for i in top_k_indices]
    ids_bm25   = [corpus_ids[i]   for i in top_k_indices]

    # ── 3. Combinar resultados eliminando duplicados ───────────────────────────
    vistos   = set()
    docs_combinados  = []
    metas_combinados = []

    for doc, meta, id_ in zip(
        docs_semantica + docs_bm25,
        metas_semantica + metas_bm25,
        ids_semantica + ids_bm25
    ):
        if id_ not in vistos:
            vistos.add(id_)
            docs_combinados.append(doc)
            metas_combinados.append(meta)

    # ── 4. ReRank con cross-encoder ───────────────────────────────────────────
    # El cross-encoder recibe pares (consulta, documento) y devuelve un score de relevancia
    pares  = [(consulta, doc) for doc in docs_combinados]
    scores = reranker.predict(pares)

    # Ordenar por score descendente y quedarse con k_final
    orden = np.argsort(scores)[::-1][:k_final]

    resultados = [
        {
            "documento": docs_combinados[i],
            "metadato":  metas_combinados[i],
            "score_rerank": float(scores[i])
        }
        for i in orden
    ]

    return resultados

In [159]:
buscar_hibrido_rerank(pregunta2)

[{'documento': 'Pregunta: ¿De qué materiales está hecho?\n Respuesta: El Caloventor II de PureAir está diseñado para uso doméstico. Revise el manual del producto (código P0171) para más detalles. Ante cualquier duda, contacte a nuestro servicio de atención al cliente.',
  'metadato': {'id_producto': 'P0171',
   'categoria': 'Especificaciones',
   'fecha_publicacion': '2025-03-11',
   'nombre_producto': 'Caloventor II'},
  'score_rerank': -7.051164627075195},
 {'documento': 'Pregunta: ¿Cuál es la forma correcta de encenderlo?\n Respuesta: El Olla de Cocción Lenta II de CookElite está diseñado para uso doméstico. Revise el manual del producto (código P0083) para más detalles. Ante cualquier duda, contacte a nuestro servicio de atención al cliente.',
  'metadato': {'categoria': 'Uso',
   'id_producto': 'P0083',
   'fecha_publicacion': '2025-02-16',
   'nombre_producto': 'Olla de Cocción Lenta II'},
  'score_rerank': -7.899877548217773},
 {'documento': 'Pregunta: ¿Cuáles son las dimensiones?\n Respuesta: El Vinoteca II de HomeChef está diseñado para uso doméstico. Revise el manual del producto (código P0119) para más detalles. Ante cualquier duda, contacte a nuestro servicio de atención al cliente.',
  'metadato': {'id_producto': 'P0119',
   'fecha_publicacion': '2025-03-06',
   'nombre_producto': 'Vinoteca II',
   'categoria': 'Especificaciones'},
  'score_rerank': -8.150808334350586}]

### Función de llamada a LLM

Para realizar una función que realice llamadas se seguirá usando Llama 3.2, alojado en local. Este modelo es adecuado porque es open source y puede ejecutarse localmente via Ollama sin configuración compleja. Por otro lado, tiene buen soporte para español a pesar de ser un modelo relativamente chico. Además, para las tareas específicas del sistema (clasificación de intención, generación de queries estructuradas (SQL, Cypher) y respuestas sobre un tema acotado) no se necesita un modelo de 70B parámetros.
Asimismo, se elige un modelo de ubicación local permite no tener costo por token y no tiene dependencia de internet ni latencia de red. Paralelamente, usar un servicio en la nube implica enviar esos datos a servidores externos, lo cual puede ser un problema de privacidad y confidencialidad, en el caso de que fuera una empresa no ficticia.

In [162]:
system_prompt_generador = """
Sos un asistente virtual especializado en productos de electrodomésticos.
Tu tarea es responder la consulta del usuario basándote únicamente en el contexto provisto.

Reglas:
- Respondé siempre en el mismo idioma de la consulta.
- Si el contexto no contiene información suficiente, indicá amablemente que no encontraste información relevante y sugerí al usuario reformular su pregunta.
- Sé claro y conciso, sin inventar información que no esté en el contexto.
"""

In [163]:
def llamar_llm_generador(consulta, contexto):
    """
    LLM Generador: recibe la consulta del usuario y el contexto
    recuperado por el pipeline y genera una respuesta final.
    """
    url = "http://localhost:11434/api/generate"

    prompt = f"""Consulta del usuario: {consulta}

Contexto recuperado:
{contexto}

Respondé la consulta basándote únicamente en el contexto provisto."""

    payload = {
        "model": "llama3.2",
        "system": system_prompt_generador,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.3}  # Se agrega algo de creatividad para más naturalidad
    }

    response = requests.post(url, json=payload)
    return response.json()["response"].strip()

In [191]:
def formatear_contexto(resultado, tipo):

    if tipo == "VECTORIAL":
        docs = resultado.get("documentos", [])
        return "\n\n".join(docs) if docs else "Sin resultados."

    elif tipo == "VECTORIAL_HIBRIDO":
        return "\n\n".join(
            [r["documento"] for r in resultado]
        ) if resultado else "Sin resultados."

    elif tipo == "TABULAR":
        if hasattr(resultado, "to_string"):
            return resultado.to_string(index=False) if not resultado.empty else "Sin resultados."
        return str(resultado)

    elif tipo == "GRAFO":
        if not isinstance(resultado, list) or not resultado:
            return "Sin resultados."
        
        # Limitar a 10 reseñas para no saturar el contexto del LLM
        muestra = resultado[:10]
        lineas = []
        for r in muestra:
            usuario  = r.get("u.id_usuario", "Desconocido")
            puntaje  = r.get("r.puntaje", "-")
            texto    = r.get("r.texto", "")
            producto = r.get("p.nombre", "")
            lineas.append(f"- {usuario} ({producto}, {puntaje}/5): {texto}")
        
        total = len(resultado)
        resumen = f"Se encontraron {total} reseñas. Mostrando las primeras 10:\n\n"
        return resumen + "\n".join(lineas)

    return "Sin resultados."

### Generación y Conversación

In [165]:
from collections import deque

In [186]:
system_prompt_preparacion = """
Sos un asistente que decide si una consulta necesita buscar información nueva o puede responderse con el historial de conversación.
Respondé únicamente con SI o NO, sin explicaciones ni caracteres extra.

SI → la consulta requiere buscar información nueva (producto, precio, reseña, uso, etc.)
NO → la consulta puede responderse con el historial previo (saludos, seguimientos, agradecimientos, referencias a lo ya dicho)

Ejemplos:

Consulta: ¿Cuáles son las licuadoras de menos de $200?
SI

Consulta: ¿Y cuánto cuesta la más barata?
NO

Consulta: ¿Qué opinan los usuarios de la cafetera?
SI

Consulta: ¿Me podés dar más detalles sobre la primera?
NO

Consulta: Hola, ¿cómo estás?
NO

Consulta: ¿Y tiene garantía?
NO

Consulta: ¿Cómo uso mi licuadora para hacer smoothies?
SI

Consulta: Gracias, eso es todo lo que necesitaba
NO

Consulta: ¿Cada cuánto debo hacer mantenimiento de mi licuadora?
SI

Consulta: ¿Cómo cuido mi electrodoméstico?
SI

Consulta: ¿Qué debo hacer para que dure más?
SI
"""

In [167]:
def preparar_consulta(consulta):
    """
    Decide si la consulta necesita recuperación de información
    o puede responderse con el historial. Devuelve True si necesita búsqueda, False si no.
    """
    url = "http://localhost:11434/api/generate"
    payload = {
        "model": "llama3.2",
        "system": system_prompt_preparacion,
        "prompt": f"Consulta: {consulta}",
        "stream": False,
        "options": {"temperature": 0}}
    response = requests.post(url, json=payload)
    resultado = response.json()["response"].strip().upper()
    return resultado == "SI"

In [168]:
def pipeline_conversacional(consulta, historial, filtros=None, k_hibrido=3):
    """
    Pipeline RAG completo con memoria conversacional y preparación de consulta.
    """

    # Preparación de consulta
    necesita_busqueda = preparar_consulta(consulta)

    if not necesita_busqueda:
        historial_str = ""
        for turno in historial:
            rol = "Usuario" if turno["rol"] == "usuario" else "Asistente"
            historial_str += f"{rol}: {turno['mensaje']}\n"

        respuesta = llamar_llm_generador(
            consulta=consulta,
            contexto=f"Historial de conversación:\n{historial_str if historial_str else 'Sin historial previo.'}")

        historial.append({"rol": "usuario",   "mensaje": consulta})
        historial.append({"rol": "asistente", "mensaje": respuesta})

        print(f"[Preparación]: Sin búsqueda, respondiendo con historial")
        print(f"[Respuesta]: {respuesta}\n")
        return respuesta

    # Clasificar intención
    intencion = clasificar_intencion_llm(consulta)

    if intencion == "ERROR":
        respuesta = "No pude entender tu consulta. ¿Podés reformularla?"
        historial.append({"rol": "usuario",   "mensaje": consulta})
        historial.append({"rol": "asistente", "mensaje": respuesta})
        return respuesta

    # Recuperar contexto según la intención
    if intencion == "VECTORIAL":
        resultado = buscar_hibrido_rerank(consulta, filtros=filtros, k_final=k_hibrido)
        contexto  = formatear_contexto(resultado, "VECTORIAL_HIBRIDO")

    elif intencion == "TABULAR":
        resultado = buscar_productos(consulta)
        contexto  = formatear_contexto(resultado, "TABULAR")

    elif intencion == "GRAFO":
        resultado = buscar_en_grafo(consulta)
        contexto  = formatear_contexto(resultado, "GRAFO")

    # Se construye contexto aumentado con historial
    historial_str = ""
    for turno in historial:
        rol = "Usuario" if turno["rol"] == "usuario" else "Asistente"
        historial_str += f"{rol}: {turno['mensaje']}\n"

    consulta_con_historial = f"""Historial de conversación:
{historial_str if historial_str else "Sin historial previo."}

Consulta actual: {consulta}"""

    # Respuesta final
    respuesta = llamar_llm_generador(consulta_con_historial, contexto)

    # Se actualiza historial
    historial.append({"rol": "usuario",   "mensaje": consulta})
    historial.append({"rol": "asistente", "mensaje": respuesta})

    print(f"[Preparación]: Búsqueda necesaria")
    print(f"[Intención detectada]: {intencion}")
    print(f"[Respuesta]: {respuesta}\n")

    return respuesta

In [184]:
historial = deque(maxlen=6)
pipeline_conversacional("¿Cuáles son las licuadoras de menos de $400?", historial)

[Preparación]: Búsqueda necesaria
[Intención detectada]: TABULAR
[Respuesta]: Para encontrar licuadoras con un precio inferior a $400, puedo revisar los precios de las licuadoras que ya he recuperado del contexto.

En este caso, solo hay dos licuadoras que se ajustan a este criterio:

1.  **P0003 Plus Licuadora Pro**: Su precio es de $329.07.
2.  **P0004 Compacto Licuadora**: Su precio es de $259.42.

Ambas son opciones viables para aquellos interesados en adquirir una licuadora a un precio razonable.

'Para encontrar licuadoras con un precio inferior a $400, puedo revisar los precios de las licuadoras que ya he recuperado del contexto.\n\nEn este caso, solo hay dos licuadoras que se ajustan a este criterio:\n\n1.  **P0003 Plus Licuadora Pro**: Su precio es de $329.07.\n2.  **P0004 Compacto Licuadora**: Su precio es de $259.42.\n\nAmbas son opciones viables para aquellos interesados en adquirir una licuadora a un precio razonable.'

In [188]:
pipeline_conversacional("¿Cómo uso mi licuadora para hacer smoothies?", historial)

[Preparación]: Búsqueda necesaria
[Intención detectada]: VECTORIAL
[Respuesta]: Para hacer smoothies con tu licuadora, te sugiero revisar el manual del producto (código P0003 o P0004) para obtener instrucciones específicas sobre cómo usarla correctamente.

En general, las licuadoras funcionan de la siguiente manera:

1.  Llena la licuadora con hielo y los ingredientes que desees procesar.
2.  Cierra la tapa y asegúrate de que esté bien cerrada para evitar fugas de líquido.
3.  Ajusta el nivel de líquido según sea necesario, dejando un poco de espacio entre los ingredientes y las paredes de la licuadora.
4.  Conecta la licuadora a una fuente de alimentación eléctrica y enciéndela.
5.  Registra el tiempo que deseas procesar tus ingredientes en la licuadora, ajustando según sea necesario para lograr tu textura deseada.

Recuerda revisar el manual del producto para obtener instrucciones específicas sobre cómo usarla correctamente.

'Para hacer smoothies con tu licuadora, te sugiero revisar el manual del producto (código P0003 o P0004) para obtener instrucciones específicas sobre cómo usarla correctamente. \n\nEn general, las licuadoras funcionan de la siguiente manera: \n\n1.  Llena la licuadora con hielo y los ingredientes que desees procesar.\n2.  Cierra la tapa y asegúrate de que esté bien cerrada para evitar fugas de líquido.\n3.  Ajusta el nivel de líquido según sea necesario, dejando un poco de espacio entre los ingredientes y las paredes de la licuadora.\n4.  Conecta la licuadora a una fuente de alimentación eléctrica y enciéndela.\n5.  Registra el tiempo que deseas procesar tus ingredientes en la licuadora, ajustando según sea necesario para lograr tu textura deseada.\n\nRecuerda revisar el manual del producto para obtener instrucciones específicas sobre cómo usarla correctamente.'

In [192]:
pipeline_conversacional("¿Qué opinan los usuarios de la cafetera?", historial)

[Cypher generado]: MATCH (u:Usuario)-[:ESCRIBIO]->(r:Reseña)-[:SOBRE]->(p:Producto)
WHERE toLower(p.nombre) CONTAINS 'cafetera'
RETURN u.id_usuario, r.puntaje, r.texto, p.nombre

[Preparación]: Búsqueda necesaria
[Intención detectada]: GRAFO
[Respuesta]: Basado en las 54 reseñas encontradas, se puede observar que los usuarios de la cafetera tienen opiniones muy variadas sobre su rendimiento y calidad. Algunos usuarios, como Bianca Benítez, Laura Vega, Emanuel Medina, Ignacio Álvarez, Francisco Martínez, Lorenzo Vargas, Agustina Flores, Martina Aguilar y Emma Mendoza, han tenido experiencias positivas con la cafetera, destacando su funcionalidad, velocidad, versatilidad, durabilidad y relación calidad-precio. Por otro lado, otros usuarios, como Lucas Rojas, han tenido experiencias negativas, criticando el producto por ser voluminoso e inestable.

En general, parece que la cafetera tiene una tasa de satisfacción alta entre los usuarios, quienes destacan sus características positivas y mencionan que es un producto de buena calidad. Sin embargo, también se encuentran algunos usuarios que critican el producto por ciertas razones, lo que sugiere que puede haber algunas limitaciones o defectos en la cafetera.

En resumen, los usuarios de la cafetera parecen tener opiniones muy variadas sobre su rendimiento y calidad, pero en general, se pueden destacar las características positivas del producto.

'Basado en las 54 reseñas encontradas, se puede observar que los usuarios de la cafetera tienen opiniones muy variadas sobre su rendimiento y calidad. Algunos usuarios, como Bianca Benítez, Laura Vega, Emanuel Medina, Ignacio Álvarez, Francisco Martínez, Lorenzo Vargas, Agustina Flores, Martina Aguilar y Emma Mendoza, han tenido experiencias positivas con la cafetera, destacando su funcionalidad, velocidad, versatilidad, durabilidad y relación calidad-precio. Por otro lado, otros usuarios, como Lucas Rojas, han tenido experiencias negativas, criticando el producto por ser voluminoso e inestable.\n\nEn general, parece que la cafetera tiene una tasa de satisfacción alta entre los usuarios, quienes destacan sus características positivas y mencionan que es un producto de buena calidad. Sin embargo, también se encuentran algunos usuarios que critican el producto por ciertas razones, lo que sugiere que puede haber algunas limitaciones o defectos en la cafetera.\n\nEn resumen, los usuarios de la cafetera parecen tener opiniones muy variadas sobre su rendimiento y calidad, pero en general, se pueden destacar las características positivas del producto.'